/** Host-owned product metadata and offline upstream attributions. */

/** Fixed release identity; imported by Host consumers only. */
export const productIdentity = Object.freeze({
  name: 'Local-Harness-pi',
  version: '0.1.5-alpha.2',
  appId: 'io.localharness.pi',
  officialDisclaimer: 'Local-Harness-pi is not an official OpenAI or DeepSeek product.',
  dsh: Object.freeze({ commit: 'b2e3b2a0125854567a4a5fcba75782e42fe84901', license: 'MIT' }),
  pi: Object.freeze({ version: '0.85.1', license: 'MIT' }),
  codex: Object.freeze({ commit: '73a1148c9c775c2a4616ce5096291740a00ed68a', usage: 'design-reference-only' }),
})

/** Exact UTF-8 contents of the packaged offline notice. */
export const thirdPartyNotices: string = 'Local-Harness-pi third-party notices\n\nDeepSeek Harness\nhttps://github.com/deepseek-ai/deepseek-harness\nb2e3b2a0125854567a4a5fcba75782e42fe84901\n\nMIT License\n\nCopyright (c) 2026 DeepSeek\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associated documentation files (the "Software"), to deal\nin the Software without restriction, including without limitation the rights\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the Software is\nfurnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\nSOFTWARE.\n\nPi\nhttps://github.com/earendil-works/pi\nacaa253cc8e3f159e6100b6f3874861b1f0bfc99\n@earendil-works/pi-agent-core 0.85.1\n@earendil-works/pi-ai 0.85.1\n\nMIT License\n\nCopyright (c) 2025 Mario Zechner\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associated documentation files (the "Software"), to deal\nin the Software without restriction, including without limitation the rights\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the Software is\nfurnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\nSOFTWARE.\n\nOpenAI Codex — design reference only; no Codex source is redistributed\nhttps://github.com/openai/codex\n73a1148c9c775c2a4616ce5096291740a00ed68a\nApache License 2.0\nhttps://www.apache.org/licenses/LICENSE-2.0\nCodex is a design reference, not a distributed component.\n'
